export default new Map<string, string>([
  ["stjärna", "⭐️"],
  ["krona", "👑"],
  ["hjärta", "💕"],
  ["hjärna", "🧠"],
  ["tand", "🦷"],
  ["katt", "😻"],
  ["fjäril", "🦋"],
  ["bi", "🐝"],
  ["ankunge", "🐥"],
  ["apa", "🐒"],
  ["lejon", "🦁"],
  ["mus", "🐭"],
  ["kanin", "🐰"],
  ["ko", "🐮"],
  ["tiger", "🐯"],
  ["panda", "🐼"],
  ["spindel", "🕷"],
  ["fisk", "🐠"],
  ["gris", "🐷"],
  ["groda", "🐸"],
  ["snigel", "🐌"],
  ["nyckelpiga", "🐞"],
  ["krabba", "🦀"],
  ["äpple", "🍏"],
  ["bröd", "🍞"],
  ["sallad", "🥗"],
  ["kiwi", "🥝"],
  ["gurka", "🥒"],
  ["boll", "⚽️"],
]);
